#!/bin/sh /etc/rc.common
# Copyright (C) 2014 DataArt

DH_SERVER="http://52.1.3.193/dh/rest"
GATEWAY_ID="openwrt-blegw"

START=98

EXTRA_COMMANDS="status"
EXTRA_HELP="
        status  Check the gateway's alive status"

PROG=/usr/bin/blegw
PID_F=/tmp/blegw.pid

start()
{
	# start daemon
	while ! hciconfig hci0 up; do
		sleep 1
	done
	start-stop-daemon -q -S -p ${PID_F} -m -a ${PROG} -- --server ${DH_SERVER} --gatewayId ${GATEWAY_ID} --helper /usr/bin/bluepy-helper &
}


stop()
{
	# stop daemon
	start-stop-daemon -q -K -p ${PID_F}

	# cleanup pid file
	rm -f ${PID_F}
}


# alive status: 0 - alive, 1 - dead
status()
{
	[ -f ${PID_F} ] && { ps -p `cat ${PID_F}` > /dev/null 2>&1; }
}
